services:
  - type: web
    name: beneath-the-blue
    env: python
    runtime: python-3.11
    buildCommand: pip install -r requirements.txt && python manage.py migrate
    startCommand: python manage.py collectstatic --noinput && gunicorn Beneath_the_blue.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: Beneath_the_blue.settings
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*.onrender.com"
      - key: DJANGO_LOG_LEVEL
        value: INFO
      