# Generated by Django 5.2.4 on 2025-07-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_quiz_remove_quizresult_user_delete_option_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='loging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='quiz',
            name='score',
            field=models.IntegerField(),
        ),
    ]
