# Generated by Django 5.2.4 on 2025-07-22 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_loging_alter_quiz_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='options',
            new_name='answer',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='score',
        ),
    ]
