# Generated by Django 5.2.4 on 2025-07-26 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_threat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('detailed_description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='solutions/')),
                ('wikipedia_link', models.URLField(blank=True, null=True)),
                ('implementation_steps', models.TextField(blank=True, null=True)),
                ('benefits', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_threat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='community.threat')),
            ],
        ),
    ]
