# Generated by Django 5.2.4 on 2025-07-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0009_solution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threat',
            name='solution',
        ),
        migrations.AddField(
            model_name='threat',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='threats/'),
        ),
        migrations.AddField(
            model_name='threat',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
