# Generated by Django 5.2.4 on 2025-08-05 09:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0014_remove_post_file_remove_post_like_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='endangered_species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('feedback_type', models.CharField(choices=[('explorer', 'Depth Explorer'), ('education', 'Learning Content'), ('action', 'Take Action'), ('general', 'General Feedback')], max_length=50)),
                ('message', models.TextField()),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('pollution', 'Pollution Solutions'), ('research', 'Marine Research'), ('education', 'Ocean Education'), ('tech', 'Conservation Tech')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('eliminate_plastics', models.BooleanField(default=False)),
                ('sustainable_seafood', models.BooleanField(default=False)),
                ('join_cleanups', models.BooleanField(default=False)),
                ('reduce_footprint', models.BooleanField(default=False)),
                ('support_conservation', models.BooleanField(default=False)),
                ('personal_promise', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EndangeredSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='photos/')),
                ('audio', models.FileField(upload_to='audios/')),
                ('des', models.TextField(default='No description available')),
                ('url', models.URLField(blank=True, null=True)),
                ('threat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endangered_species', to='community.endangered_species')),
            ],
        ),
    ]
