# Generated by Django 5.2.4 on 2025-08-05 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0015_endangered_species_feedback_idea_pledge_subscriber_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solution',
            old_name='wikipedia_link',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='benefits',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='detailed_description',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='implementation_steps',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='related_threat',
        ),
        migrations.AlterField(
            model_name='solution',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
